### ISSUE TITLE
Shouldn't the return type of <.> be real-valued?

### ISSUE THREAD

**Issue by ocramz** [conal/vector-space#19]
The inner product of two, say, arrays of Complex numbers should be purely real, but the current implementation returns a Complex with imaginary part equal to 0.

What's the rationale behind this choice?

**Comment by leftaroundabout** [comment]
With what particular instance do you get that behaviour? Actually `<.>` _does_ give a real number at the moment, since e.g. `Scalar (Complex Double, Complex Double) ~ Double`.

IMO it shouldn't yield a real number, though! The `magnitudeSq` of a complex vector should always be real, but the inner product of to _different_ vectors may not. E.g. [(1,_i_) · (_i_,1) = 2·_i_](http://www.wolframalpha.com/input/?i=%5B1,i%5D+*+%5Bi,1%5D). With `(Complex Double, Complex Double)`, this gives the rather nonsensical result 0 instead.

So, I'd rather support the _opposite_ issue...

**Comment by ocramz** [comment]
@leftaroundabout You're absolutely right, my bad. I was thinking about the L2 norm induced by `<.>`. I don't use tuples in this context so I hadn't noticed, but now that you point it out I see it is incorrect.
The mistake is https://github.com/conal/vector-space/blob/master/src/Data/VectorSpace.hs#L145

**Comment by ocramz** [comment]
@leftaroundabout @conal I will open another issue once I'll gather a few motivating examples.
